### ISSUE TITLE
Option to save name list entered in text field

### ISSUE THREAD

**Issue by sekjal** [stringham/raffle#6]
Noticing at Code4Lib 2016 that each raffle run requires a refresh and copy/paste of the registration list again.  It would be great if the pasted list could be saved to local storage by checking a box underneath the text entry field, since we typically run 3-8 giveaways in a row.

**Comment by stringham** [comment]
If you click on the winning name after the raffle finishes it resets with the names that were entered.

**Comment by sekjal** [comment]
Oh!  Didn't see that feature in use.  Thanks!
